/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_qihoo_com_jnicrash_CrashHandler */

#ifndef _Included_test_qihoo_com_jnicrash_CrashHandler
#define _Included_test_qihoo_com_jnicrash_CrashHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_qihoo_com_jnicrash_CrashHandler
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_qihoo_com_jnicrash_CrashHandler_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
